name: Sync Claude Knowledge

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      force_sync:
        description: 'Force full sync'
        type: boolean
        required: false
        default: false

jobs:
  sync-knowledge:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      CLAUDE_CODE_AUTH_TOKEN: ${{ secrets.CLAUDE_CODE_AUTH_TOKEN }}
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        submodules: recursive

    - name: Update submodules
      run: |
        git submodule update --init --recursive
        git submodule foreach 'git fetch origin && git reset --hard origin/$(git rev-parse --abbrev-ref HEAD) || git reset --hard origin/master'

    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected in submodules"
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "chore: Sync submodules and knowledge base

        Auto-sync performed by GitHub Actions

        Generated with [Claude Code](https://claude.ai/code)
        via [Happy](https://happy.engineering)

        Co-Authored-By: Claude <noreply@anthropic.com>
        Co-Authored-By: Happy <yesreply@happy.engineering>"
        git push